### PR TITLE
Sprint 1/issue 3#create the rest of the screens

### LINKED ISSUE #3: Create the rest of the screens.
## DESCRIPTION

- [ ] Create home flow screens.
- [ ] Create resources flow screens.
- [ ] Create settings screen.

### PR DESCRIPTION
**Pull request by Lizzflores**
# Description

What did you implemented/Why did you implemented this:

-Created the screens needed for our home and resources sections. In the "Home" section, we designed a user-friendly interface that allows easy navigation through various features and functionalities. The "Resources" section provides users with a comprehensive library of educational content, including songs, podcasts, and interactive materials to read. We aimed to create visually appealing and intuitive screens to enhance the user experience and promote engagement with the app's content.

## Screenshots
image
image
image

### CODE REVIEW

**Review by Tole15 — APPROVED** [review]

**Review by BrandonVG — APPROVED** [review]
image

**Review by Eduardoespl — APPROVED** [review]
LGTM! 🚀

**Comment by J3fte** [comment]
Buen diseño

**Comment by Tole15** [comment]
image

**Pull request merged**
