### PR TITLE
Sprint 3/issue 26#reading practice api

### LINKED ISSUE #26: Reading Practice API
## REQUIREMENTS / DESCRIPTION

> This issue is related to the API that provides texts for the Reading Practice screen. The API should return strings of texts to be displayed in the cards of the screen.

## DESIGN

image

### PR DESCRIPTION
**Pull request by Lizzflores**
# Description

This pull request includes a new feature that enhances the reading screen by integrating an external API to fetch and display short stories. It also incorporates a FlatList component to elegantly present the fetched stories as cards.

## Screenshots
api-reading

### CODE REVIEW

**Review by BrandonVG — APPROVED** [review]
https://github.com/BrightCoders-Institute/proyecto-final-rn-teamb/assets/54459465/6e0cf4d8-0c8e-4713-95f1-fb145c4c6a42

**Review by FebernalGober — APPROVED** [review]
LGTM

**Review by ShadowEnchanter — APPROVED** [review]
Good Job!

**Review by AlbertoG22 — APPROVED** [review]
Texto alternativo

**Pull request merged**
